name: Success Test
on:
  workflow_dispatch:

jobs:
  success-job:
    name: Job will succeeed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Success Step
        uses: ./.github/actions/dummy-action
